language: r

# Don't fail just for warnings (though these need to be fixed for CRAN)
warnings_are_errors: false

sudo: required

r_check_args: --no-examples

notifications:
  email: false

r_github_packages:
  - aiorazabala/qmethod

after_success:
  - codecov

bash <(curl -s https://codecov.io/bash) -t 31e04eaa-bbf2-4268-91fa-2e09fd7a031e
